### ISSUE TITLE
Precise version of fmod to link

### ISSUE THREAD

**Issue by Stargateur** [GuillaumeGomez/rust-fmod#11]
I try to compile on windows and I have trouble.

I link with **fmod64_vc.lib**, but they are 68 symbol missing, I try with other version available. that lead me to have 67 (???) symbol missing.

I didn't find any information on the fmod version of your binding. Can you precise it somewhere ?

**Comment by GuillaumeGomez** [comment]
I don't remember the version but you can get it here: http://www.guillaume-gomez.fr/fmodapi44439linux.tar.gz

**Comment by Stargateur** [comment]
Thanks, I can link with 4.44.46 of FMOD Designer.

But it's look like FMOD has change a lot. They don't let you download FMOD Ex for free.
And they API has change to a different name and version.
Now it's FMOD Studio, and the API is 1.x.
http://www.fmod.org/documentation/#content/generated/overview/transitioning.html

**Comment by GuillaumeGomez** [comment]
Yes, thqt's exactly why I think this is the last version I'll support.
