### ISSUE TITLE
get_driver_info() panics due to "FromUtf8Error"

### ISSUE THREAD

**Issue by ghtyrant** [GuillaumeGomez/rust-fmod#22]
I try to enumerate drivers on my system using the following code:

```rust
let num_drivers = fmod.get_num_drivers().expect("Failed to enumerate drivers.");
for i in 0..num_drivers {
    let driver_name = match fmod.get_driver_info(i, 256usize) {
        Ok((_, name)) => {info!("Driver: {}", name); name},
        Err(e) => {error!("get_driver_info error: {:?}", e); "".into()}
    };
}
```

This fails with the following panic:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [75, 111, 112, 102, 104, 246, 114, 101, 114, 32, 40, 50, 45, 32, 72, 105, 103, 104, 32, 68, 101, 102, 105, 110, 105, 116, 105, 111, 110, 32, 65, 117, 100, 105, 111, 45, 71, 101, 114, 228, 116, 41, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], error: Utf8Error { valid_up_to: 5, error_len: Some(1) } }', libcore\result.rs:945:5
```

I'm on Windows 7, using Rust stable (1.25.0)
I have playback devices containing German umlauts - could this be the issue? The device in question is called "Kopfhörer".

**Comment by GuillaumeGomez** [comment]
It shouldn't be... I certainly have some `unwrap` calls around. I'll write fix quickly.

**Comment by ghtyrant** [comment]
FYI, sorry I didn't mention this earlier: I'm using version 4.44.41 of fmodex. This is the closest version I could find to 4.44.39. I also tried 4.44.59 with the same result.

**Comment by GuillaumeGomez** [comment]
The version shouldn't matter, don't worry. It's just me that did bad work at some places. :-/

**Comment by GuillaumeGomez** [comment]
Can you check again please?

**Comment by ghtyrant** [comment]
The panic is gone, get_driver_info() now correctly returns an Error! Thanks for your quick work.
Looks like non of my drivers name can be decoded using UTF-8 though. Do you know why this is the case and what I can do to get the names anyway?

**Comment by GuillaumeGomez** [comment]
Let's go for the second one then. Do you want to send a PR?

**Comment by ghtyrant** [comment]
Will do, once I get back home from work.

Can we conclude that the documentation of FMOD's `System::getDriverInfo()` is wrong and that the function does not return correct UTF-8, at least on some systems?

**Comment by GuillaumeGomez** [comment]
I assume so. :-/
