### ISSUE TITLE
create_sound with default soundex info results in InvalidParam when run in release mode

### ISSUE THREAD

**Issue by spearman** [GuillaumeGomez/rust-fmod#25]
Here is a minimal example that will return 'Err(InvalidParam)' when run with the `--release` flag, but not when running debug builds:

```
extern crate rfmod;

macro_rules! rfmod_ok {
  ($e:expr) => {
    assert_eq!($e, rfmod::Status::Ok)
  }
}

fn main() {
  let rfmod_sys    = rfmod::Sys::new().unwrap();
  const MAX_CHANNELS : i32 = 16;
  rfmod_ok!(rfmod_sys.init_with_parameters (
    MAX_CHANNELS, rfmod::InitFlag (rfmod::INIT_3D_RIGHTHANDED)));
  println!("...rfmod sys initialized...");

  let listener_position = rfmod::Vector { x: 0.0, y: 0.0, z: 2.0 };
  let listener_velocity = rfmod::Vector { x: 0.0, y: 0.0, z: 0.0 };
  let forward           = rfmod::Vector { x: 0.0, y: 0.0, z: -1.0 };
  let up                = rfmod::Vector { x: 0.0, y: 1.0, z: 0.0 };
  rfmod_ok!(rfmod_sys.set_3D_listener_attributes (
    0, &listener_position, &listener_velocity, &forward, &up));
  println!("...rfmod sys 3d listener attributes set...");

  let mut default_soundex_info  = rfmod::CreateSoundexInfo::default();
  let rfmod_sound = rfmod_sys.create_sound (
    "ping.wav",
    //Some (rfmod::Mode (rfmod::_3D | rfmod::SOFTWARE)),
    None,
    Some (&mut default_soundex_info)
  ).unwrap();
  println!("...rfmod wav sound created...");
}
```

I've tried with the commented out 'Mode' with the same result.

**Comment by GuillaumeGomez** [comment]
I wrote this binding years ago so a few versions might have been released since then. The problem might come from this? I won't have much time to look into but if you're motivated enough to make a PR, I'll gladly merge it.

**Comment by spearman** [comment]
I'll dig into it and see what I can figure out. There are two examples in this repository that use the CreateSoundexInfo struct and set some fields, but they didn't result in the error.

**Comment by spearman** [comment]
There doesn't seem to be any difference in the FMOD_CREATESOUNDEXINFO types between the two versions and linking against the correct version doesn't fix the error.

A slightly more minimal example is:
```
extern crate rfmod;

macro_rules! rfmod_ok {
  ($e:expr) => {
    assert_eq!($e, rfmod::Status::Ok)
  }
}

fn main() {
  let rfmod_sys = rfmod::Sys::new().unwrap();
  rfmod_ok!(rfmod_sys.init_with_parameters (16, rfmod::InitFlag (rfmod::INIT_NORMAL)));
  println!("...rfmod sys initialized...");
  println!("fmod version: {}", rfmod_sys.get_version().unwrap());
  let mut default_soundex_info  = rfmod::CreateSoundexInfo::default();
  let rfmod_sound = rfmod_sys.create_sound (
    "ping.wav",
    Some (rfmod::Mode (rfmod::DEFAULT)),
    Some (&mut default_soundex_info)
  ).unwrap();
  println!("...rfmod wav sound created...");
}
```
which I take to be about equivalent to this C version:
```
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "include/fmod.h"

int main () {
  printf ("fmod version: %u\n", FMOD_VERSION);
  FMOD_RESULT result;
  FMOD_SYSTEM *system = NULL;
  result = FMOD_System_Create(&system);
  if (result != FMOD_OK) {
    printf("FMOD error! (%d)\n", result);
    exit(-1);
  }
  result = FMOD_System_Init(system, 16, FMOD_INIT_NORMAL, NULL);
  if (result != FMOD_OK) {
    printf("FMOD error! (%d)\n", result);
    exit(-1);
  }
  unsigned int version;
  result = FMOD_System_GetVersion (system, &version);
  printf ("linked version: %u\n", version);
  if (result != FMOD_OK) {
    printf("FMOD error! (%d)\n", result);
    exit(-1);
  }
  FMOD_SOUND *sound = NULL;
  FMOD_CREATESOUNDEXINFO info;
  memset (&info, 0, sizeof (FMOD_CREATESOUNDEXINFO));
  info.cbsize = sizeof (FMOD_CREATESOUNDEXINFO);
  result = FMOD_System_CreateSound(
    system, "ping.wav", FMOD_DEFAULT, &info, &sound);
  if (result != FMOD_OK) {
    printf("FMOD error! (%d)\n", result);
    exit(-1);
  }
  puts ("...sound created...");
}
```
The main difference in the C version is that the struct is initialized to zero, but even if I do the same for the struct in the Rust version (keeping the cbsize field equal to 216) it still results in 'InvalidParam', but *only* for the --release build.

**Comment by spearman** [comment]
Here's some output linking against the 'logging' FMOD library (#[link(name = "fmodexL64")] extern{}):

debug: https://gist.github.com/spearman/ce21d3524b1cc19945d013caf7325a8f

release: https://gist.github.com/spearman/7f47938a392bf60e209e9d24650f05b9

Version information all indicates 04.44.39 (corresponds to the u32 version value 279609).

In the log of the release build you can see some fields of exinfo become garbage, and 'cbsize' somehow becomes '0', although I added a print statement in the 'create_sound' function right after it is converted showing that it should be '216', before it is passed to the creation function. So I guess I'm kind of stumped, no idea why this would be happening in a release build but not debug.

**Comment by GuillaumeGomez** [comment]
Maybe a bug on rust side but I have to admit that I have difficulties to understand why it would change a variable size... Maybe it's less permissive?
