### ISSUE TITLE
example in readme seems out of date

### ISSUE THREAD

**Issue by DanielCollins** [GuillaumeGomez/rust-fmod#3]
to get it to compile I have to change

`rfmod::FmodSys::new` to `rfmod::Sys`
`StrBuf::from_str` to `&String::from`
`panic!("Error code : {}", err);` to `panic!("Error code : {:?}", err);`

and remove `extern crate libc;`

I am not sure if all these changes are completely correct, because it compiles, but it only works sometimes. under some circumstances it fails with FileNotFound, and strace shows that it is calling `open()` with extra random characters on the end of the file path. I'm not sure if that's related to my `&String` change or something else.

**Comment by GuillaumeGomez** [comment]
Hum... I made little changes recently and examples built fine on my computer. If it's randomly crashing, that's not good at all. I'll try to fix it as soon as possible (in 2-3 days I hope).

Thanks for reporting it !

**Comment by DanielCollins** [comment]
Actually, with those changes to get it compile, the resulting readme example binary works perfectly every time.

The filename problem occurs only when I try to integrate it into my larger project. So I guess I should open a new issue for that when I can work out a minimal test case.

**Comment by GuillaumeGomez** [comment]
Really ? Could you open a PR with your fix then please ? It'll fix the immediate issue while waiting for your minimal test case. :)

**Comment by DanielCollins** [comment]
fixed in #4
