### ISSUE TITLE
eta on new release for cargo?

### ISSUE THREAD

**Issue by DanielCollins** [GuillaumeGomez/rust-fmod#8]
not a bug, just a question. i would like my users to be able to `cargo install` the recent improvements. can i help with anything?

**Comment by GuillaumeGomez** [comment]
No, I just need to repack it, it will be done today.

**Comment by GuillaumeGomez** [comment]
And it's done. Thanks for your contributions !

**Comment by DanielCollins** [comment]
thank you!
